# Generated by Django 2.2.4 on 2019-08-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dietaryrestriction',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
